services:
  # user service
  user-service:
    build:
      context: ../../user_service/user-service
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - ../../user_service/user-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - db-user
      - redis-user
      - kafka
    networks:
      - backend-network
    restart: unless-stopped

  # user postgres
  db-user:
    image: postgres:15-alpine
    container_name: db-user
    env_file:
      - ../../user_service/user-service/.env
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-userdb}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # user redis
  redis-user:
    image: redis:7-alpine
    container_name: redis-user
    command: redis-server --appendonly yes
    volumes:
      - redis_user_data:/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_user_data:
  redis_user_data:

networks:
  backend-network:
    external: true
